//      This file is used to build mdidemo.hlp file
//      It is used also too build the map dictionary
//      for HelpManager
//      Look at MDIDemo class>>buildMapDictionary method

#define Demo            100
#define doc1            106
#define doc2            107
#define exit            109

#define View            201
#define toggleStatusPane 202
#define toggleToolPane  203

#define comboBox_    204
#define toolPane_    205
#define statusPane_  206
