\* 
    Puzzle15.h:  Text resource header file.
*\

#define    ApplicationTitle        100    
#define    HelpMenuTitle            101
#define    HelpContents                102
#define    HelpOn                    103
#define    HelpForHelp              104

#define    PuzzleMenuTitle        105
#define    PuzzleMenu            106

#define    SolvedMessage        107

#define    SizeQueryMessage    108
#define    DefaultSize                109

#define    HelpManagerTitle    110
#define    HelpFileName          111
#define    HelpMapFileName    112
#define    VwHelpMapFileName  113

#define    FontFaceName        114
#define    CloseConfirm          115

#define    ColorDialogTitle        116
#define    FaceColorText            117
#define    BorderColorText        118
#define    OkButtonText            119
#define    CancelButtonText    120

#define    ColorBlack                121
#define    ColorDarkred            122
#define    ColorBlue                123
#define    ColorPink                    124
#define    ColorDefault            125
#define    ColorDarkgray            126
#define    ColorBrown                127
#define    ColorGreen                128
#define    ColorYellow                129
#define    ColorCyan                130
#define    ColorDarkblue            131
#define    ColorWhite                132
#define    ColorDarkcyan            133
#define    ColorBackground        134
#define    ColorDarkgreen        135
#define    ColorNeutral            136
#define    ColorRed                    137
#define    ColorPalegray            138
#define    ColorDarkpink            139
#define    ColorLightgray            140

