
(File pathName:'examples\fredrwng\biteditr.cls') fileIn; close!
Smalltalk at: #ExecutableFileFormatConstants put: nil!
(File pathName:'examples\iconedit\iconst.txt') fileIn; close!
(File pathName:'examples\iconedit\resource.cls') fileIn; close!
(File pathName:'examples\iconedit\exefile.cls') fileIn; close!
(File pathName:'examples\iconedit\icondilg.cls') fileIn; close!
(File pathName:'examples\iconedit\iconedtr.cls') fileIn; close!
